version: '3.8'

services:
  reverseproxy:
    container_name: reverseproxy
    restart: always
    build:
      context: .
      dockerfile: ./docker/reverseproxy/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./docker/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  playground:
    container_name: playground
    restart: always
    tty: true
    build:
      context: .
      dockerfile: ./docker/playground/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - playground_volumes:/workspace
    depends_on:
      - db
  db:
    container_name: db
    #restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db_volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  playground_volumes:
  db_volumes:
