export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/admin/favicon.ico' sizes='any' />
        <title>Admin</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
